# Generated by Django 6.0.8 on 2026-08-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100, verbose_name='اسم الفرع أو المعمل')),
                ('branch_code', models.CharField(max_length=20, unique=True, verbose_name='الرمز المحلي')),
                ('status', models.CharField(default='متاح', max_length=50, verbose_name='حالة المعمل')),
            ],
        ),
    ]
