# Generated by Django 6.0.8 on 2026-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labbranch',
            options={'verbose_name': 'معمل', 'verbose_name_plural': 'المعامل'},
        ),
        migrations.RemoveField(
            model_name='labbranch',
            name='status',
        ),
        migrations.AddField(
            model_name='labbranch',
            name='capacity',
            field=models.IntegerField(default=20, verbose_name='السعة الاستيعابية'),
        ),
        migrations.AddField(
            model_name='labbranch',
            name='description',
            field=models.TextField(default=1, verbose_name='وصف مختصر للأنشطة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labbranch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_images/', verbose_name='صورة المعمل'),
        ),
        migrations.AddField(
            model_name='labbranch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='هل المعمل متاح حالياً؟'),
        ),
        migrations.AddField(
            model_name='labbranch',
            name='location',
            field=models.CharField(default=0, max_length=200, verbose_name='موقع المعمل (مثل: مبنى أ - الدور 2)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labbranch',
            name='branch_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='كود المعمل'),
        ),
        migrations.AlterField(
            model_name='labbranch',
            name='branch_name',
            field=models.CharField(max_length=150, verbose_name='اسم المعمل'),
        ),
    ]
