# Generated by Django 6.0.8 on 2026-08-20 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_labbranch_options_remove_labbranch_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_count', models.IntegerField(verbose_name='عدد أجهزة الكمبيوتر')),
                ('os_system', models.CharField(max_length=50, verbose_name='نظام التشغيل')),
                ('lab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='branches.labbranch', verbose_name='المعمل')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('student_id', models.CharField(max_length=20, verbose_name='الرقم الجامعي')),
                ('laboratories', models.ManyToManyField(related_name='students', to='branches.labbranch', verbose_name='المعامل المسجلة')),
            ],
        ),
    ]
