# Generated by Django 6.0.8 on 2026-08-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_labspecification_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labbranch',
            options={},
        ),
        migrations.RemoveField(
            model_name='labspecification',
            name='os_system',
        ),
        migrations.RemoveField(
            model_name='labspecification',
            name='pc_count',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='laboratories',
        ),
        migrations.AddField(
            model_name='labspecification',
            name='spec_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labspecification',
            name='spec_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labbranch',
            name='branch_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='labbranch',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='labbranch',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='labbranch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labbranch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lab_images/'),
        ),
        migrations.AlterField(
            model_name='labbranch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='labbranch',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labspecification',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='branches.labbranch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
