# Generated by Django 6.0.8 on 2026-08-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_course_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('student_id', models.CharField(max_length=50, verbose_name='الرقم الجامعي')),
                ('lab_name', models.CharField(max_length=100, verbose_name='اسم المعمل المطلوب')),
                ('booking_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
            ],
        ),
    ]
