# Generated by Django 6.0.8 on 2026-08-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_studentlabbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlabbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
