# Generated by Django 6.0.8 on 2026-08-07 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=100, verbose_name='اسم المعمل')),
                ('booking_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('time_slot', models.CharField(max_length=50, verbose_name='وقت الجلسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الطلب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='الطالب')),
            ],
        ),
    ]
